// <auto-generated />
namespace RepositoriesGestionReservaSalas.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addingDbsets : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addingDbsets));
        
        string IMigrationMetadata.Id
        {
            get { return "201701201424115_adding-Dbsets"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
